services:

  zookeeper: 
    image: zookeeper
    container_name: zookeeper
    volumes:
      - ./zookeeper:/data

  kafka: 
    image: bitnami/kafka
    container_name: kafka
    volumes:
      - ./kafka:/bitnami/kafka/data
    ports:
      - 9092:9092
    environment:
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://localhost:9092 #if want to connect kafka
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
    depends_on:
      - zookeeper #wating zookeeper fitst